server:
  port: 9999
spring:
  datasource:
    username: root
    password: xduniversity20
    url: jdbc:mysql://localhost:3306/bilibili?useSSL=false
  redis:
    database: 3
    host: 192.168.184.100
    port: 6379
    password: xduniversity20

logging:
  level:
    com.huang: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1